using FluentChaining;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using RichEntity.Generation.Entity.Commands;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace RichEntity.Generation.Entity.CommentHeaderBuilding;

public class AutoGeneratedCommentBuilder : ILink<CommentHeaderBuildingCommand, UsingDirectiveSyntax>
{
    public UsingDirectiveSyntax Process(
        CommentHeaderBuildingCommand request,
        SynchronousContext context,
        LinkDelegate<CommentHeaderBuildingCommand, SynchronousContext, UsingDirectiveSyntax> next)
    {
        const string comment =
            @"// <auto-generated>
// This code was generated by a RichEntity code generator.
// https://github.com/ronimizy/RichEntity
// </auto-generated>
";

        var autoGeneratedComment = TriviaList(Comment(comment));
        var autoGeneratedCommentToken = Token(autoGeneratedComment, SyntaxKind.UsingKeyword, TriviaList());

        request = request with
        {
            Syntax = request.Syntax.WithUsingKeyword(autoGeneratedCommentToken),
        };

        return next(request, context);
    }
}